export default {
    settings() {
        return {
            0: {
                items: [{
                    name: 'apple',
                    img: 'apple',
                    x: 837,
                    y: 276,
                    size: 100
                }, {
                    name: 'apple',
                    img: 'apple',
                    x: 107,
                    y: 655,
                    size: 160
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 257,
                    y: 163, 
                    size: 65,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 364,
                    y: 130,
                    size: 70,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 1005,
                    y: 201,
                    size: 80
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 365,
                    y: 318,
                    size: 90
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 611,
                    y: 281,
                    size: 70
                }],
                winningCriteria: {
                    items: ['apple', 'apple'],
                    xMin: 864,
                    xMax: 1435,
                    yMin: 413,
                    yMax: 843,  
                }
            },
            1: {
                items: [{
                    name: 'apple',
                    img: 'apple',
                    x: 80,
                    y: 161,
                    size: 100
                }, {
                    name: 'apple',
                    img: 'apple',
                    x: 89,
                    y: 587,
                    size: 160
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 257,
                    y: 163, 
                    size: 65,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 364,
                    y: 130,
                    size: 70,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 1005,
                    y: 201,
                    size: 170,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 911,
                    y: 436,
                    size: 70,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 593,
                    y: 268,
                    size: 100
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 332,
                    y: 403,
                    size: 150
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 1041,
                    y: 52,
                    size: 70
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 789,
                    y: 423,
                    size: 70
                }, {
                    name: 'pineapple',
                    img: 'pineapple',
                    x: 134,
                    y: 530,
                    size: 170
                }, {
                    name: 'pineapple',
                    img: 'pineapple',
                    x: 1186,
                    y: 195,
                    size: 70
                }],
                winningCriteria: {
                    items: ['apple', 'apple', 'blueberry', 'pineapple'],
                    xMin: 864,
                    xMax: 1435,
                    yMin: 413,
                    yMax: 843, 
                }  
            },
            2: {
                items: [{
                    name: 'apple',
                    img: 'apple',
                    x: 139,
                    y: 114,
                    size: 100,
                }, {
                    name: 'apple',
                    img: 'apple',
                    x: 1248,
                    y: 228,
                    size: 80,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 292,
                    y: 140, 
                    size: 65,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 378,
                    y: 227,
                    size: 70,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 1105,
                    y: 201,
                    size: 70,
                }, {
                    name: 'mango',
                    img: 'mango',
                    x: 1219,
                    y: 163,
                    size: 180,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 619,
                    y: 309,
                    size: 70,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 534,
                    y: 456,
                    size: 180,
                }, {
                    name: 'lemon',
                    img: 'lemon',
                    x: 1041,
                    y: 52,
                    size: 180,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 789,
                    y: 423,
                    size: 90,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 609,
                    y: 198,
                    size: 70,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 363,
                    y: 308,
                    size: 70,
                }, {
                    name: 'raspberry',
                    img: 'raspberry',
                    x: 1208,
                    y: 209,
                    size: 80,
                }, {
                    name: 'pineapple',
                    img: 'pineapple',
                    x: 864,
                    y: 278,
                    size: 70,
                }, {
                    name: 'pineapple',
                    img: 'pineapple',
                    x: 472,
                    y: 433,
                    size: 160,
                }, {
                    name: 'strawberry',
                    img: 'strawberry',
                    x: 38,
                    y: 539,
                    size: 170,
                }, {
                    name: 'watermelon',
                    img: 'watermelon',
                    x: 101,
                    y: 550,
                    size: 200,
                }],
                winningCriteria: {
                    items: ['apple', 'apple', 'blueberry', 'pineapple', 'watermelon', 'strawberry'],
                    xMin: 864,
                    xMax: 1435,
                    yMin: 413,
                    yMax: 843, 
                }  
            }
        }
    }
}