export default {
    settings() {
        return {
            0: {
                items: [{
                    name: 'apple',
                    img: 'apple',
                    x: 837,
                    y: 276,
                    size: 100
                }, {
                    name: 'apple',
                    img: 'apple',
                    x: 237,
                    y: 655,
                    size: 160
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 257,
                    y: 163, 
                    size: 65,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 364,
                    y: 140,
                    size: 70,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 1000,
                    y: 201,
                    size: 80
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 365,
                    y: 318,
                    size: 90
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 611,
                    y: 281,
                    size: 70
                }],
                winningCriteria: {
                    items: ['apple', 'apple'],
                    xMin: 832,
                    xMax: 1200,
                    yMin: 413,
                    yMax: 790, 
                }
            },
            1: {
                items: [{
                    name: 'apple',
                    img: 'apple',
                    x: 280,
                    y: 261,
                    size: 100
                }, {
                    name: 'apple',
                    img: 'apple',
                    x: 289,
                    y: 587,
                    size: 110
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 257,
                    y: 163, 
                    size: 65,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 364,
                    y: 130,
                    size: 70,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 1005,
                    y: 201,
                    size: 80,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 911,
                    y: 436,
                    size: 70,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 593,
                    y: 268,
                    size: 100
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 332,
                    y: 403,
                    size: 110
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 1041,
                    y: 152,
                    size: 70
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 789,
                    y: 423,
                    size: 70
                }, {
                    name: 'pineapple',
                    img: 'pineapple',
                    x: 234,
                    y: 530,
                    size: 110
                }, {
                    name: 'pineapple',
                    img: 'pineapple',
                    x: 1086,
                    y: 195,
                    size: 70
                }],
                winningCriteria: {
                    items: ['apple', 'apple', 'blueberry', 'pineapple'],
                    xMin: 832,
                    xMax: 1200,
                    yMin: 413,
                    yMax: 790, 
                }  
            },
            2: {
                items: [{
                    name: 'apple',
                    img: 'apple',
                    x: 240,
                    y: 114,
                    size: 100,
                }, {
                    name: 'apple',
                    img: 'apple',
                    x: 1248,
                    y: 228,
                    size: 80,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 292,
                    y: 140, 
                    size: 65,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 378,
                    y: 227,
                    size: 70,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 1105,
                    y: 201,
                    size: 70,
                }, {
                    name: 'mango',
                    img: 'mango',
                    x: 1219,
                    y: 163,
                    size: 120,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 619,
                    y: 309,
                    size: 70,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 534,
                    y: 456,
                    size: 110,
                }, {
                    name: 'lemon',
                    img: 'lemon',
                    x: 1041,
                    y: 152,
                    size: 120,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 789,
                    y: 423,
                    size: 90,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 609,
                    y: 198,
                    size: 70,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 363,
                    y: 308,
                    size: 70,
                }, {
                    name: 'raspberry',
                    img: 'raspberry',
                    x: 1008,
                    y: 209,
                    size: 80,
                }, {
                    name: 'pineapple',
                    img: 'pineapple',
                    x: 864,
                    y: 278,
                    size: 70,
                }, {
                    name: 'pineapple',
                    img: 'pineapple',
                    x: 472,
                    y: 433,
                    size: 120,
                }, {
                    name: 'strawberry',
                    img: 'strawberry',
                    x: 238,
                    y: 539,
                    size: 110,
                }, {
                    name: 'watermelon',
                    img: 'watermelon',
                    x: 230,
                    y: 550,
                    size: 100,
                }],
                winningCriteria: {
                    items: ['apple', 'apple', 'blueberry', 'pineapple', 'watermelon', 'strawberry'],
                    xMin: 832,
                    xMax: 1200,
                    yMin: 413,
                    yMax: 790, 
                }  
            }
        }
    }
}