export default {
    settings() {
        return {
            0: {
                items: [{
                    name: 'apple',
                    img: 'apple',
                    x: 80,
                    y: 161,
                    size: 100
                }, {
                    name: 'apple',
                    img: 'apple',
                    x: 526,
                    y: 642,
                    size: 60
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 257,
                    y: 163, 
                    size: 65,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 364,
                    y: 130,
                    size: 70,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 1005,
                    y: 201,
                    size: 80
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 289,
                    y: 469,
                    size: 90
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 522,
                    y: 600,
                    size: 70
                }],
                winningCriteria: {
                    items: ['apple', 'apple'],
                    xMin: 734,
                    xMax: 1074,
                    yMin: 511,
                    yMax: 720,  
                }
            },
            1: {
                items: [{
                    name: 'apple',
                    img: 'apple',
                    x: 80,
                    y: 161,
                    size: 100
                }, {
                    name: 'apple',
                    img: 'apple',
                    x: 526,
                    y: 642,
                    size: 60
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 257,
                    y: 163, 
                    size: 65,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 364,
                    y: 130,
                    size: 70,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 1005,
                    y: 201,
                    size: 70,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 1144,
                    y: 289,
                    size: 70,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 1005,
                    y: 201,
                    size: 80
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 290,
                    y: 570,
                    size: 90
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 522,
                    y: 600,
                    size: 70
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 289,
                    y: 469,
                    size: 70
                }, {
                    name: 'pineapple',
                    img: 'pineapple',
                    x: 400,
                    y: 700,
                    size: 70
                }, {
                    name: 'pineapple',
                    img: 'pineapple',
                    x: 389,
                    y: 569,
                    size: 70
                }],
                winningCriteria: {
                    items: ['apple', 'apple', 'blueberry', 'pineapple'],
                    xMin: 734,
                    xMax: 1074,
                    yMin: 511,
                    yMax: 720,  
                }  
            },
            2: {
                items: [{
                    name: 'apple',
                    img: 'apple',
                    x: 80,
                    y: 161,
                    size: 100
                }, {
                    name: 'apple',
                    img: 'apple',
                    x: 526,
                    y: 642,
                    size: 60
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 257,
                    y: 163, 
                    size: 65,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 364,
                    y: 130,
                    size: 70,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 1005,
                    y: 201,
                    size: 70,
                }, {
                    name: 'mango',
                    img: 'mango',
                    x: 905,
                    y: 301,
                    size: 80,
                }, {
                    name: 'cherry',
                    img: 'cherry',
                    x: 1144,
                    y: 289,
                    size: 70,
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 1005,
                    y: 201,
                    size: 80
                }, {
                    name: 'lemon',
                    img: 'lemon',
                    x: 805,
                    y: 501,
                    size: 180
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 290,
                    y: 570,
                    size: 90
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 522,
                    y: 600,
                    size: 70
                }, {
                    name: 'blueberry',
                    img: 'blueberry',
                    x: 289,
                    y: 469,
                    size: 70
                }, {
                    name: 'raspberry',
                    img: 'raspberry',
                    x: 600,
                    y: 300,
                    size: 80
                }, {
                    name: 'pineapple',
                    img: 'pineapple',
                    x: 400,
                    y: 700,
                    size: 70
                }, {
                    name: 'pineapple',
                    img: 'pineapple',
                    x: 389,
                    y: 569,
                    size: 70
                }, {
                    name: 'strawberry',
                    img: 'strawberry',
                    x: 589,
                    y: 669,
                    size: 170
                }, {
                    name: 'watermelon',
                    img: 'watermelon',
                    x: 689,
                    y: 769,
                    size: 80
                }],
                winningCriteria: {
                    items: ['apple', 'apple', 'blueberry', 'pineapple', 'watermelon', 'strawberry'],
                    xMin: 734,
                    xMax: 1074,
                    yMin: 511,
                    yMax: 720,  
                }  
            }
        }
    }
}